css-canvas-medical Challenge | Jared Gilleland
ejgilleland/m1-1120-code-solutions pull request #21
Opened 2020-12-11 05:09 UTC by ejgilleland

***50% zoom, full screen (the best way for me to fit all the lines in this screenshot!):

![image](https://user-images.githubusercontent.com/73370554/101865699-dcdc7500-3b2b-11eb-9cfd-9c9ad0247217.png)

2020-12-11 05:09 UTC, ejgilleland commented
Please don't flame me; this challenge crushed my spirit LOL

2020-12-11 05:24 UTC, uzair-ashraf requested changes

2020-12-11 05:24 UTC, uzair-ashraf commented on css-canvas-medical/styles.css
> +}
the content of the text should be arranged using margin and padding , it is not a valid use for absolute positioning

2021-01-05 23:13 UTC, uzair-ashraf approved these changes

2021-01-06 02:34 UTC, merged